name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vector-search-chat:$(date +%s)
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1
